# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constans import globalConstans
from utilitiessss import Driver, ConfigReader

class TestInvalidLogin():
    def setup_method(self, method):
        self.driver = Driver.get_driver()
        self.driver.get(ConfigReader.read_config("url"))
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_invalidLogin(self):
        WebDriverWait(self.driver, 5).until(
            expected_conditions.visibility_of_element_located((By.ID, globalConstans.username_id)))
        self.driver.find_element(By.ID, globalConstans.username_id).send_keys("1")
        WebDriverWait(self.driver, 5).until(
            expected_conditions.visibility_of_element_located((By.ID, globalConstans.password_id)))
        self.driver.find_element(By.ID, globalConstans.password_id).send_keys("1")
        WebDriverWait(self.driver, 5).until(
            expected_conditions.visibility_of_element_located((By.ID, globalConstans.login_button_id)))
        self.driver.find_element(By.ID, globalConstans.login_button_id).click()
        assert self.driver.find_element(By.CSS_SELECTOR,
                                        "*[data-test=\"error\"]").text == "Epic sadface: Username and password do not match any user in this service"